const soldiers =[
    {
        name:'אביב אלמו',
        email:'aviv2107@gmail.com',
        personalNumber:'8803992',
        weapon:'מיקרו תבור / m 16',
        isRight:true,
        shoeSize:42,
        uniformSize:'מ',
        foodPref:'הכל',
        job:'שליח',
        phone:'0526497006',
        education:'',

    },
    {
        name:'אביב פרץ',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'אביעד ציונית',
        email:'aviadtzionit@gmail.com',
        personalNumber:'7644875',
        weapon:'מיקרו תבור',
        isRight:true,
        shoeSize:45,
        uniformSize:'2ב',
        foodPref:'הכל',
        job:'סטודנט',
        phone:'0525662605',
        education:'סטודנט לכלכלה',

    },
    {
        name:'אביצח אלחיאני',
        email:'avitzah77@gmail.com',
        personalNumber:'7643937',
        weapon:'M16',
        isRight:true,
        shoeSize:43,
        uniformSize:'2ב',
        foodPref:'הכל',
        job:'סוכן ביטוח',
        phone:'0525546133',
        education:'',

    },
    {
        name:'אברהם סבחט',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'אדם גרינברג',
        email:'adamgri85@gmail.com',
        personalNumber:'7453134',
        weapon:'M16',
        isRight:true,
        shoeSize:44,
        uniformSize:' ב',
        foodPref:'טבעוני',
        job:'מהנדס חמרה (אינטל)',
        phone:'0528901322',
        education:'תואר ראשון הנדסת חשמל תואר שני מנהל עסקים',

    },
    {
        name:'אהרן הררי',
        email:'ronih339@gmail.com',
        personalNumber:'5221920',
        weapon:'m16',
        isRight:true,
        shoeSize:41,
        uniformSize:'',
        foodPref:'הכל',
        job:'טכנאי בבזק',
        phone:'0506775471',
        education:'',

    },
    {
        name:'אופיר אביעוז',
        email:'ofir.ex@hotmail.com',
        personalNumber:'8814676',
        weapon:'מיקרו תבור / M16',
        isRight:true,
        shoeSize:44,
        uniformSize:'ב',
        foodPref:'הכל',
        job:'מאבטח אחיד ממלכתי',
        phone:'0522195955',
        education:'',

    },
    {
        name:'אורי נתן',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'אוריאל סיידה',
        email:'Ourielsayada@gmail.com',
        personalNumber:'8269540',
        weapon:'מיקרו תבור',
        isRight:true,
        shoeSize:44,
        uniformSize:'ג',
        foodPref:'הכל',
        job:'עמיל מכס',
        phone:'0528281710',
        education:'בגרות',

    },
    {
        name:'אורן סבהט',
        email:'orenz8843@gmail.com',
        personalNumber:'8730521',
        weapon:'מיקרו תבור',
        isRight:true,
        shoeSize:42,
        uniformSize:'ב',
        foodPref:'הכל',
        job:'טבח בבר',
        phone:'0537263453',
        education:'',

    },
    {
        name:'אורן קוגמאן',
        email:'Orenku123@gmail.com',
        personalNumber:'5308049',
        weapon:'M16',
        isRight:false,
        shoeSize:43,
        uniformSize:'2ב',
        foodPref:'הכל',
        job:'מנהל פרויקטים',
        phone:'0506523046',
        education:'עו״ד',

    },
    {
        name:'אטירסאו אדיס',
        email:'dystrsw@gmil.com',
        personalNumber:'5780814',
        weapon:'מיקרו תבור/M16',
        isRight:false,
        shoeSize:40,
        uniformSize:'ק',
        foodPref:'הכל',
        job:'',
        phone:'0548180186',
        education:'',

    },
    {
        name:'איגור בייזנוב',
        email:'bezie1985@gmail.com',
        personalNumber:'5328203',
        weapon:'M16',
        isRight:true,
        shoeSize:46,
        uniformSize:'מ',
        foodPref:'הכל',
        job:'מהנדס תחזוקה אונ בן גוריון',
        phone:'054-2283936',
        education:'מהנדס מכונות',

    },
    {
        name:'אלון רבייב',
        email:'alonrabaev@gmail.com',
        personalNumber:'8756143',
        weapon:'מיקרו תבור/ M16',
        isRight:true,
        shoeSize:42,
        uniformSize:'ב2',
        foodPref:'הכל',
        job:'מאבטח מתקדם א נמל חיפה',
        phone:'0544883508',
        education:'',

    },
    {
        name:'אליאל קלאפהולץ',
        email:'Elielkl@hotmail.com ',
        personalNumber:'7522480',
        weapon:'מיקרו תבור +תבור ',
        isRight:true,
        shoeSize:42,
        uniformSize:'ב2',
        foodPref:'הכל',
        job:'סטודנט לרפואה',
        phone:'0544253506',
        education:'רפואה/פסיכולוגיה ',

    },
    {
        name:'אליה דדשב',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'אלכסנדר איווניצקי',
        email:'alexander_im@hotmail.com',
        personalNumber:'5884163',
        weapon:'Tavor/M16/M24/Mag',
        isRight:true,
        shoeSize:44,
        uniformSize:'XL',
        foodPref:'',
        job:'צלם/אבטחה',
        phone:'0523677661',
        education:'תואר ראשון',

    },
    {
        name:'אלעד ריטן',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'אלעד מדמון',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'אנדריי גריץ',
        email:'andrijgeru4@gmail.com',
        personalNumber:'8101890',
        weapon:'מיקרו תבור+m16',
        isRight:true,
        shoeSize:43,
        uniformSize:'2ב',
        foodPref:'הכל',
        job:'מאבטח',
        phone:'0533364176',
        education:'',

    },
    {
        name:'בועז וולף',
        email:'boazwolf13@gmail.com',
        personalNumber:'8771771',
        weapon:'מיקרו תבור',
        isRight:false,
        shoeSize:42,
        uniformSize:'ב2',
        foodPref:'הכל',
        job:'מאמן כושר',
        phone:'0584750234',
        education:'',

    },
    {
        name:'בועז שרעבי',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'בנימין זדנג',
        email:'bennyzhruaia@gmail.com',
        personalNumber:'7417749',
        weapon:'m4 קלעים ',
        isRight:true,
        shoeSize:42,
        uniformSize:'ק2',
        foodPref:'הכל',
        job:'תחזוקה( אב בית)',
        phone:'0548112993',
        education:'',

    },
    {
        name:'בנימין לוי',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'ברוך אניואו',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'ברוך מססה',
        email:'Baruch7080@gmail.com',
        personalNumber:'8755157',
        weapon:'M-16+מיקרו תבור',
        isRight:true,
        shoeSize:42,
        uniformSize:'ק2',
        foodPref:'הכל',
        job:'עובד טבח',
        phone:'052-891-6001',
        education:'',

    },
    {
        name:'גד קוסטה',
        email:'Gadkosta540@gmail.com',
        personalNumber:'7595285',
        weapon:'מיקרו תבור, תבור, m16',
        isRight:true,
        shoeSize:44,
        uniformSize:'ג2',
        foodPref:'הכל',
        job:'מנהל תפעול ברשת rooms',
        phone:'054-2120880 ',
        education:'תואר ראשון ותעודת הוראה',

    },
    {
        name:'גיא איתן',
        email:'guy1.etyan@gmail.com',
        personalNumber:'8038702',
        weapon:'מיקרו תבור + אם 16',
        isRight:false,
        shoeSize:45,
        uniformSize:'ב2',
        foodPref:'הכל',
        job:'בוגר תואר בהנדסת תעשייה וניהול',
        phone:'0526220409',
        education:'תואר ראשון',

    },
    {
        name:'גיא כהן',
        email:'Guy4501@gmail.com',
        personalNumber:'8752647',
        weapon:'מיקרו תבור/m16',
        isRight:true,
        shoeSize:42,
        uniformSize:'ק2',
        foodPref:'הכל',
        job:'מאבטח',
        phone:'0547739106',
        education:'',

    },
    {
        name:'גלעד מאירסון',
        email:'gilad.meirson@gmail.com',
        personalNumber:'7655977',
        weapon:'מיקרו תבור + אמ 16 + נגב',
        isRight:true,
        shoeSize:44.5,
        uniformSize:'ג2',
        foodPref:'הכל',
        job:'מהנדס מערכות מידע',
        phone:'0512122453',
        education:'תואר ראשון',

    },
    {
        name:'דביר שטרית',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'דוד זאקשובר',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'דוד חייפץ',
        email:'hefetzdavid@gmail.com',
        personalNumber:'8192628',
        weapon:'מיקרו תבור + אם 16',
        isRight:true,
        shoeSize:44,
        uniformSize:'ג',
        foodPref:'הכל',
        job:'סטודנט',
        phone:'0508131533',
        education:'',

    },
    {
        name:'דוד יחזקאל',
        email:'Dudiyehezkel@gmail.com',
        personalNumber:'',
        weapon:'מיקרו תבור',
        isRight:true,
        shoeSize:43,
        uniformSize:'2ב',
        foodPref:'הכל',
        job:'מהנדס מכונות',
        phone:'0508589679',
        education:'תואר ראשון',

    },
    {
        name:'דור לובטון',
        email:'dorloubaton@gmail.com',
        personalNumber:'7582644',
        weapon:'M16',
        isRight:true,
        shoeSize:42,
        uniformSize:'2ב',
        foodPref:'הכל',
        job:'קצין משטרה',
        phone:'0502299267',
        education:'תואר ראשון קרימינולוגיה',

    },
    {
        name:'דייויד אהרוני',
        email:'Davidaharonig@gmail.com',
        personalNumber:'8246971',
        weapon:'מיקרו תבור/M4/M16',
        isRight:true,
        shoeSize:42,
        uniformSize:'ק2/ב',
        foodPref:'הכל',
        job:'פיקוח בנייה+סטודנט',
        phone:'0525444780',
        education:'',

    },
    {
        name:'דניאל איסקוב',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'דניאל זכות',
        email:'danielz490@gmail.com',
        personalNumber:'8367176',
        weapon:'מיקרו תבור/אם 16',
        isRight:true,
        shoeSize:46,
        uniformSize:'ג',
        foodPref:'הכל',
        job:'לומד בישיבה',
        phone:'0504269128',
        education:'',

    },
    {
        name:'הבטמו דסטה',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'זאב בלאוגרונד',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'זוהר כהן',
        email:'Zoharcps4@gmail.com',
        personalNumber:'8130914',
        weapon:'מיקרו+m-16',
        isRight:true,
        shoeSize:42,
        uniformSize:'ק',
        foodPref:'טבעוני',
        job:'סטודנט לפסיכולוגיה',
        phone:'0502265158',
        education:'תואר ראשון',

    },
    {
        name:'טקלה גארד',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'יאיר חנימוב',
        email:'hthtr0@gmail.com',
        personalNumber:'8217107',
        weapon:'מיקרו תבור/m 16/נגב',
        isRight:true,
        shoeSize:44,
        uniformSize:'ב',
        foodPref:'הכל',
        job:'מהנדס תוכנה',
        phone:'0525969970',
        education:'תואר ראשון',

    },
    {
        name:'יבגני יודקוביץ',
        email:'Yudku7@gmail.com ',
        personalNumber:'5379845',
        weapon:'תבור',
        isRight:true,
        shoeSize:44,
        uniformSize:'ג',
        foodPref:'הכל',
        job:'מהנדס תוכנה',
        phone:'0526004723',
        education:'תואר ראשון',

    },
    {
        name:'ידידיה עשוש',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'יהב מלקו',
        email:'yahav28701@gmail.com',
        personalNumber:'8801385',
        weapon:'מיקרו תבור',
        isRight:true,
        shoeSize:48,
        uniformSize:'ב',
        foodPref:'הכל',
        job:'מאבטח',
        phone:'0548854529',
        education:'',

    },
    {
        name:'יהונתן קזיאב',
        email:'yonni455@gmail.com',
        personalNumber:'8256393',
        weapon:'m16',
        isRight:true,
        shoeSize:42,
        uniformSize:'ב',
        foodPref:'הכל',
        job:'מאבטח',
        phone:'0549134988',
        education:'ייעוץ פנסיוני',

    },
    {
        name:'יהונתן שפילמן',
        email:'yehonatandavid12@gmail.com',
        personalNumber:'5664411',
        weapon:'מיקרו תבור קלע/ m16',
        isRight:true,
        shoeSize:41,
        uniformSize:'ק',
        foodPref:'הכל',
        job:'הוראה',
        phone:'0545441401',
        education:'',

    },
    {
        name:'יובל ברזלב',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'יובל שניצר',
        email:'yovel1990@gmail.com',
        personalNumber:'7502978',
        weapon:'תבור',
        isRight:true,
        shoeSize:43,
        uniformSize:'ג',
        foodPref:'הכל',
        job:'מתכנן תנועה',
        phone:'0546304161',
        education:'',

    },
    {
        name:'יוחאי ברזילי',
        email:'yohaybar29@gmail.com',
        personalNumber:'7425461',
        weapon:'m4 קלעים',
        isRight:false,
        shoeSize:42,
        uniformSize:'ב',
        foodPref:'הכל',
        job:'אחראי מחשבים בבית ספר',
        phone:'0503035920',
        education:'',

    },
    {
        name:'יוסף שרגא',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'יחיאל קסאי',
        email:'Kasayyehiel@gmail.com',
        personalNumber:'8086727',
        weapon:'',
        isRight:true,
        shoeSize:40,
        uniformSize:'ק',
        foodPref:'הכל',
        job:'',
        phone:'0509715868',
        education:'',

    },
    {
        name:'יצחק בן-גיגי',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'יקותיאל אזרחי',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'ליאור בדני',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'ליאור דוד',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'ליאור רותם',
        email:'lliioorr.rr@gmail.com',
        personalNumber:'6403283',
        weapon:'M16',
        isRight:true,
        shoeSize:43.5,
        uniformSize:'ממ',
        foodPref:'הכל',
        job:'דובר ועדת הכלכלה של הכנסת',
        phone:'050-6200143',
        education:'',

    },
    {
        name:'ליעד אמור',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'מור מחלוף',
        email:'mormor2580@gmail.com',
        personalNumber:'8578249',
        weapon:'m4 / מיקרו תבור',
        isRight:false,
        shoeSize:44,
        uniformSize:'2ב',
        foodPref:'הכל',
        job:'מתקין חלונות אלומניום',
        phone:'052-3338623',
        education:'',

    },
    {
        name:'מוריס אוחנה',
        email:'morisohana86@gmail.com',
        personalNumber:'7678205',
        weapon:'מטול',
        isRight:true,
        shoeSize:42,
        uniformSize:'ק',
        foodPref:'הכל',
        job:'עצמאי',
        phone:'0548013937',
        education:'',

    },
    {
        name:'מיטל פורסטר',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'מיכאל אוחנה',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'מיכאל לירן',
        email:'',
        personalNumber:'8666634',
        weapon:'מיקרו תבור/מאג',
        isRight:true,
        shoeSize:45,
        uniformSize:'ג',
        foodPref:'הכל',
        job:'מאבטח',
        phone:'0548024663',
        education:'',

    },
    {
        name:'מעין עמרם',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'מרדכי נמטלשוילי',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'מרו סמלין',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'מרום הררי',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'מתן גדג',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'מתן חפץ',
        email:'matanc389@gmail.com',
        personalNumber:'8023127',
        weapon:'',
        isRight:true,
        shoeSize:41,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'0545464869',
        education:'',

    },
    {
        name:'מתן משה קליין',
        email:'matan050260@gmail.com',
        personalNumber:'8108004',
        weapon:'מיקרו תבור+m16',
        isRight:true,
        shoeSize:42,
        uniformSize:'ב1',
        foodPref:'הכל',
        job:'',
        phone:'0502608086',
        education:'',

    },
    {
        name:'נדב אליהו',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'נהוראי בן שטרית',
        email:'Bvurth112233@gmail.com',
        personalNumber:'8469936',
        weapon:'מיקרו תבור',
        isRight:true,
        shoeSize:44,
        uniformSize:'ב',
        foodPref:'הכל',
        job:'מלצר עם כריזמה',
        phone:'0547795521',
        education:'אין',

    },
    {
        name:'ניב ראובן',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'ניר אברהם',
        email:'niravraham14@gmail.com',
        personalNumber:'8051806',
        weapon:'m16',
        isRight:true,
        shoeSize:44,
        uniformSize:'2ב',
        foodPref:'הכל',
        job:'הנדסאי חשמל - חידוש מערכות בקרה בתעשייה ( מנהל פרויקטים)',
        phone:'052-8148886',
        education:'',

    },
    {
        name:'ניתאי שירן',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'נתנאל לוי',
        email:'natilevi84@gmail.com',
        personalNumber:'7341146',
        weapon:'M-16',
        isRight:true,
        shoeSize:45,
        uniformSize:'מ2',
        foodPref:'הכל',
        job:'מהנדס תוכנה',
        phone:'0527203521',
        education:'',

    },
    {
        name:'סהר בוסקילה',
        email:'Saharbus3101@gmail.com',
        personalNumber:'8778154',
        weapon:'M-16',
        isRight:true,
        shoeSize:43,
        uniformSize:'2ב',
        foodPref:'הכל',
        job:'עבודות זמניות',
        phone:'0524323667',
        education:'',

    },
    {
        name:'סרגיי מורזחנוב',
        email:'Serjomurz@gmail.com',
        personalNumber:'7713814',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'עודד רוזנברג',
        email:'odedros@gmail.com',
        personalNumber:'7308196',
        weapon:'m16',
        isRight:true,
        shoeSize:42,
        uniformSize:'ג',
        foodPref:'הכל',
        job:'מתכנת',
        phone:'0545999263',
        education:'',

    },
    {
        name:'עוז אסטיוקאר',
        email:'oziko85@gmail.com',
        personalNumber:'7427935',
        weapon:'M16',
        isRight:true,
        shoeSize:44,
        uniformSize:'מ',
        foodPref:'הכל',
        job:'מהנדס מנהל איכות',
        phone:'054-2069396',
        education:'תואר שני בהנדסה',

    },
    {
        name:'עומר חניה',
        email:'hania61732@gmail.com',
        personalNumber:'8184204',
        weapon:'m16+מיקרו',
        isRight:true,
        shoeSize:41,
        uniformSize:'ק',
        foodPref:'הכל',
        job:'הנדסאי בניין',
        phone:'0503929008',
        education:'הנדסאי',

    },
    {
        name:'עידן  פיאמנטה',
        email:'Idanpya162@gmail.com',
        personalNumber:'8791304',
        weapon:'M-16',
        isRight:true,
        shoeSize:44,
        uniformSize:'ג2',
        foodPref:'הכל',
        job:'ביטחון ',
        phone:'050-599-5066',
        education:'',

    },
    {
        name:'עמיחי שמח',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'עמית רוזיליו',
        email:'Amit.rozilyo@gmail.com',
        personalNumber:'8755253',
        weapon:'מיקרו+m16',
        isRight:true,
        shoeSize:41,
        uniformSize:'ב',
        foodPref:'הכל',
        job:'מאמן כושר',
        phone:'054-713039-',
        education:'',

    },
    {
        name:'עמית קרימן',
        email:'amit.kriman@gmail.com',
        personalNumber:'8047741',
        weapon:'מיקרו תבור ',
        isRight:true,
        shoeSize:42.5,
        uniformSize:'ב',
        foodPref:'הכל',
        job:'מהנדס אלקטרוניקה',
        phone:'0544644600',
        education:'מהנדס',

    },
    {
        name:'עמרי דדוש',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'עפרי פרבר',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'ראזי מוקטרן',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'רון רבנסרי',
        email:'ronrevensari@gmail.com',
        personalNumber:'8245641',
        weapon:'מיקרו תבור',
        isRight:true,
        shoeSize:42,
        uniformSize:'ק',
        foodPref:'הכל',
        job:'',
        phone:'0542001432',
        education:'',

    },
    {
        name:'רונן חנוכייב',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'רזיאל אברהם',
        email:'raziel.ra29@gmail.com',
        personalNumber:'8084416',
        weapon:'m16',
        isRight:true,
        shoeSize:42,
        uniformSize:'ג',
        foodPref:'הכל',
        job:'מטמיע',
        phone:'0538229640',
        education:'ניהול מערכות בריאות',

    },
    {
        name:'רינט ולייב',
        email:'patriot2507@mail.ru',
        personalNumber:'5903920',
        weapon:'תבור, מיקרו תבור, M-16, M-4',
        isRight:true,
        shoeSize:43,
        uniformSize:'ב2',
        foodPref:'הכל',
        job:'טכנאי',
        phone:'0527503275',
        education:'',

    },
    {
        name:'רן משה ירון',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'שובל בוחבוט',
        email:'Shovalbu21@gmail.com',
        personalNumber:'8171058',
        weapon:'מיקרו תבור',
        isRight:true,
        shoeSize:42,
        uniformSize:'ב',
        foodPref:'הכל',
        job:'מהנדס מכונות',
        phone:'',
        education:'',

    },
    {
        name:'שחף טסלר',
        email:'shtes11@gmail.com',
        personalNumber:'7192871',
        weapon:'M16',
        isRight:true,
        shoeSize:44,
        uniformSize:'ג',
        foodPref:'הכל',
        job:'חקלאי',
        phone:'0526356452',
        education:'תואר ראשון',

    },
    {
        name:'שיי אריה',
        email:'shayarye95@gmail.com',
        personalNumber:'8113164',
        weapon:'M16+תבור',
        isRight:true,
        shoeSize:43,
        uniformSize:'ב2',
        foodPref:'הכל',
        job:'',
        phone:'050-8990071',
        education:'תואר שני באסטרופיזיקה קוואנטית',

    },
    {
        name:'שלומי בסון',
        email:'shlomibason@gmail.com',
        personalNumber:'5222907',
        weapon:'m16',
        isRight:true,
        shoeSize:43,
        uniformSize:'ב2',
        foodPref:'הכל',
        job:'מנהל תיקי לקוחות',
        phone:'',
        education:'',

    },
    {
        name:'שלמה קברטה',
        email:'Kabareta13@gmail.com',
        personalNumber:'8175332',
        weapon:'M16+תבור',
        isRight:true,
        shoeSize:41,
        uniformSize:'ג',
        foodPref:'הכל',
        job:'קצין ביטחון רשות האכיפה והגביה ',
        phone:'0525316556',
        education:'תואר  ראשון',

    },
    {
        name:'תומר ברוך',
        email:'Tomerbaruch95@gmail.com',
        personalNumber:'8068036',
        weapon:'M16+תבור',
        isRight:true,
        shoeSize:43,
        uniformSize:'מ',
        foodPref:'הכל',
        job:'סטודנט',
        phone:'0509731975',
        education:'תואר ראשון',

    },
    {
        name:'תומר וזנה',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:0,
        uniformSize:'',
        foodPref:'הכל',
        job:'',
        phone:'',
        education:'',

    },
    {
        name:'רן זילברמן',
        email:'',
        personalNumber:'',
        weapon:'',
        isRight:true,
        shoeSize:40,
        uniformSize:'',
        foodPref:'הכל',
        job:'Melio.com Director of engineering',
        phone:'0528455288',
        education:'מדעי המחשב',

    },
    // {
    //     name:'',
    //     email:'',
    //     personalNumber:'',
    //     weapon:'',
    //     isRight:true,
    //     shoeSize:40,
    //     uniformSize:'',
    //     foodPref:'הכל',
    //     job:'',
    //     phone:'',
    //     education:'',

    // },



]


